//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChattingAppTeam6.Properties {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ChattingAppTeam6.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap BasicImage {
            get {
                object obj = ResourceManager.GetObject("BasicImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap chat_profile_test {
            get {
                object obj = ResourceManager.GetObject("chat_profile_test", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap em1 {
            get {
                object obj = ResourceManager.GetObject("em1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap em2 {
            get {
                object obj = ResourceManager.GetObject("em2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap em3 {
            get {
                object obj = ResourceManager.GetObject("em3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap em4 {
            get {
                object obj = ResourceManager.GetObject("em4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap em5 {
            get {
                object obj = ResourceManager.GetObject("em5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap em6 {
            get {
                object obj = ResourceManager.GetObject("em6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap em7 {
            get {
                object obj = ResourceManager.GetObject("em7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap em8 {
            get {
                object obj = ResourceManager.GetObject("em8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap em9 {
            get {
                object obj = ResourceManager.GetObject("em9", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   18년
        ///18놈
        ///18새끼
        ///ㄱㅐㅅㅐㄲl
        ///ㄱㅐㅈㅏ
        ///가슴만져
        ///가슴빨아
        ///가슴빨어
        ///가슴조물락
        ///가슴주물럭
        ///가슴쪼물딱
        ///가슴쪼물락
        ///가슴핧아
        ///가슴핧어
        ///강간
        ///개가튼년
        ///개가튼뇬
        ///개같은년
        ///개걸레
        ///개고치
        ///개너미
        ///개넘
        ///개년
        ///개놈
        ///개늠
        ///개똥
        ///개떵
        ///개떡
        ///개라슥
        ///개보지
        ///개부달
        ///개부랄
        ///개불랄
        ///개붕알
        ///개새
        ///개세
        ///개쓰래기
        ///개쓰레기
        ///개씁년
        ///개씁블
        ///개씁자지
        ///개씨발
        ///개씨블
        ///개자식
        ///개자지
        ///개잡년
        ///개젓가튼넘
        ///개좆
        ///개지랄
        ///개후라년
        ///개후라들놈
        ///개후라새끼
        ///걔잡년
        ///거시기
        ///걸래년
        ///걸레같은년
        ///걸레년
        ///걸레핀년
        ///게부럴
        ///게세끼
        ///게이
        ///게새끼
        ///게늠
        ///게자식
        ///게지랄놈
        ///고환
        ///공지
        ///공지사항
        ///귀두
        ///깨쌔끼
        ///난자마셔
        ///난자먹어
        ///난자핧아
        ///내꺼빨아
        ///내꺼핧아
        ///내버지
        ///내자지
        ///내잠지
        ///내조지
        ///너거애비
        ///노옴
        ///누나강간
        ///니기미
        ///니뿡
        ///니뽕
        ///니씨브랄
        ///니아범
        ///니아비
        ///니애미
        ///니애뷔
        ///니애비
        ///니할애비
        ///닝기미
        ///닌기미
        ///니미
        ///닳은년
        ///덜은새끼
        ///돈새끼
        ///돌으년
        ///돌은넘
        ///돌은새끼
        ///동생강간
        ///동성애자
        ///딸딸이
        ///똥구녁
        ///똥꾸뇽
        ///똥구뇽
        ///똥
        ///띠발뇬
        ///띠팔
        ///띠펄
        ///띠풀
        ///띠벌
        ///띠벨
        ///띠빌
        ///마스터
        ///막간년
        ///막대쑤셔줘
        ///막대핧아줘
        ///맛간년
        ///맛없는년
        ///맛이[나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string fword_list {
            get {
                return ResourceManager.GetString("fword_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap PlusIcon {
            get {
                object obj = ResourceManager.GetObject("PlusIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
